import type { Quiz } from '@/types/content'
export const quiz: Quiz = {
  id: 'module-04-quiz', moduleSlug: 'module-04-prompt-engineering', title: 'Prompt Engineering — Quiz', passingScore: 70, xpReward: 50,
  questions: [
    { id: 'q1', text: 'What is the golden rule of prompt engineering?', options: [{ id: 'a', text: 'Keep prompts as short as possible' }, { id: 'b', text: 'Be specific' }, { id: 'c', text: 'Always use bullet points' }, { id: 'd', text: 'Write in uppercase for emphasis' }], correctOption: 'b', explanation: 'Specificity is the golden rule — vague prompts produce vague results. The more context and constraints you provide, the better the output.' },
    { id: 'q2', text: 'What does Chain of Thought prompting do?', options: [{ id: 'a', text: 'Chains multiple API calls together' }, { id: 'b', text: 'Encourages Claude to reason step by step before answering' }, { id: 'c', text: 'Links Claude to external knowledge bases' }, { id: 'd', text: 'Creates multi-model pipelines' }], correctOption: 'b', explanation: 'Chain of Thought prompting encourages Claude to show its reasoning step by step, which improves accuracy on complex tasks.' },
    { id: 'q3', text: 'Why are XML tags useful in prompts?', options: [{ id: 'a', text: 'They make prompts run faster' }, { id: 'b', text: 'They help separate instructions, context, and data clearly' }, { id: 'c', text: 'They are required by the API' }, { id: 'd', text: 'They reduce token count' }], correctOption: 'b', explanation: 'XML tags semantically label different sections of a prompt (instructions vs data vs examples), making it clear to Claude what each part is.' },
    { id: 'q4', text: 'What is few-shot prompting?', options: [{ id: 'a', text: 'Using a very short system prompt' }, { id: 'b', text: 'Providing 2-5 examples before asking Claude to do the actual task' }, { id: 'c', text: 'Making Claude answer with fewer words' }, { id: 'd', text: 'Using Haiku instead of Opus' }], correctOption: 'b', explanation: 'Few-shot prompting provides 2-5 examples demonstrating the desired input/output pattern before the actual task.' },
    { id: 'q5', text: 'What is the purpose of a system prompt?', options: [{ id: 'a', text: 'To start every user message' }, { id: 'b', text: 'To define Claude\'s persona, constraints, and behavior for the session' }, { id: 'c', text: 'To set the temperature parameter' }, { id: 'd', text: 'To specify the model version' }], correctOption: 'b', explanation: 'A system prompt runs before the conversation and sets Claude\'s persona, constraints, output format, and overall behavior.' },
    { id: 'q6', text: 'Which is the correct way to ask Claude to think before answering?', options: [{ id: 'a', text: '"Answer quickly without thinking"' }, { id: 'b', text: '"Think step by step" or use <thinking> tags' }, { id: 'c', text: '"Use your best guess"' }, { id: 'd', text: 'Set temperature to 0' }], correctOption: 'b', explanation: 'Asking Claude to "think step by step" or using <thinking> tags triggers chain-of-thought reasoning for more accurate answers.' },
  ],
}
