import type { Quiz } from '@/types/content'
export const quiz: Quiz = {
  id: 'module-05-quiz', moduleSlug: 'module-05-tool-use', title: 'Tool Use — Quiz', passingScore: 70, xpReward: 50,
  questions: [
    { id: 'q1', text: 'Who actually executes the tool function when Claude calls a tool?', options: [{ id: 'a', text: 'Claude runs it internally' }, { id: 'b', text: 'Anthropic\'s servers run it' }, { id: 'c', text: 'Your application code runs it' }, { id: 'd', text: 'A separate AI model runs it' }], correctOption: 'c', explanation: 'Claude only requests tool calls — your application code is responsible for actually executing the function and returning results.' },
    { id: 'q2', text: 'What stop_reason indicates Claude wants to call a tool?', options: [{ id: 'a', text: '"end_turn"' }, { id: 'b', text: '"tool_use"' }, { id: 'c', text: '"function_call"' }, { id: 'd', text: '"max_tokens"' }], correctOption: 'b', explanation: 'When Claude wants to call a tool, response.stop_reason equals "tool_use".' },
    { id: 'q3', text: 'What is the most important part of a tool definition for Claude to use it correctly?', options: [{ id: 'a', text: 'The tool\'s name' }, { id: 'b', text: 'The description — Claude reads it to decide when to call the tool' }, { id: 'c', text: 'The number of parameters' }, { id: 'd', text: 'The return type' }], correctOption: 'b', explanation: 'The description is what Claude reads to determine if and when to call a tool. A vague description leads to incorrect tool usage.' },
    { id: 'q4', text: 'How do you return a tool result back to Claude?', options: [{ id: 'a', text: 'As a new system prompt' }, { id: 'b', text: 'As a user message with type "tool_result"' }, { id: 'c', text: 'By calling a special results API endpoint' }, { id: 'd', text: 'Claude automatically reads the result' }], correctOption: 'b', explanation: 'Tool results are returned as a user message containing a content block with type "tool_result" and the matching tool_use_id.' },
    { id: 'q5', text: 'What enables Claude to call multiple tools simultaneously?', options: [{ id: 'a', text: 'Parallel mode setting' }, { id: 'b', text: 'Claude can return multiple tool_use blocks in one response' }, { id: 'c', text: 'Sending multiple system prompts' }, { id: 'd', text: 'Tool parallelism is not supported' }], correctOption: 'b', explanation: 'Claude can return multiple tool_use content blocks in a single response when it identifies tools that can be called in parallel.' },
    { id: 'q6', text: 'What should an agentic tool loop check to know when Claude is done?', options: [{ id: 'a', text: 'When output tokens reach zero' }, { id: 'b', text: 'When stop_reason equals "end_turn"' }, { id: 'c', text: 'After a fixed number of iterations' }, { id: 'd', text: 'When Claude says "I\'m done"' }], correctOption: 'b', explanation: 'The agentic loop should break when stop_reason equals "end_turn", meaning Claude has finished and is not requesting any more tools.' },
  ],
}
