import type { Quiz } from '@/types/content'
export const quiz: Quiz = {
  id: 'module-08-quiz', moduleSlug: 'module-08-building-apps', title: 'Building Apps with Claude — Quiz', passingScore: 70, xpReward: 50,
  questions: [
    { id: 'q1', text: 'What does RAG stand for?', options: [{ id: 'a', text: 'Rapid API Generation' }, { id: 'b', text: 'Retrieval-Augmented Generation' }, { id: 'c', text: 'Recursive Attention Graph' }, { id: 'd', text: 'Real-time AI Gateway' }], correctOption: 'b', explanation: 'RAG stands for Retrieval-Augmented Generation — combining document retrieval with Claude\'s generation to answer questions grounded in your data.' },
    { id: 'q2', text: 'What is the first step in building a RAG system?', options: [{ id: 'a', text: 'Query Claude with the user\'s question' }, { id: 'b', text: 'Chunk documents, embed them, and store in a vector database' }, { id: 'c', text: 'Fine-tune Claude on your data' }, { id: 'd', text: 'Write a detailed system prompt' }], correctOption: 'b', explanation: 'The first step is ingesting your documents: chunking them into pieces, generating embeddings, and storing them in a vector database for retrieval.' },
    { id: 'q3', text: 'What makes an AI "agent" different from a simple chatbot?', options: [{ id: 'a', text: 'Agents use larger models' }, { id: 'b', text: 'Agents autonomously plan, use tools, and iterate until a goal is met' }, { id: 'c', text: 'Agents are faster' }, { id: 'd', text: 'Agents don\'t need API keys' }], correctOption: 'b', explanation: 'Agents autonomously plan, take actions via tools, observe results, and continue iterating — unlike chatbots which just respond to single messages.' },
    { id: 'q4', text: 'Why should you always proxy Claude API calls through your server?', options: [{ id: 'a', text: 'It makes responses faster' }, { id: 'b', text: 'To keep your API key secret from clients' }, { id: 'c', text: 'Anthropic requires it' }, { id: 'd', text: 'It reduces token usage' }], correctOption: 'b', explanation: 'Always proxy through your server so the API key never reaches the client browser, where it could be stolen and misused.' },
    { id: 'q5', text: 'What is a recommended chunk size for RAG document splitting?', options: [{ id: 'a', text: '50 tokens' }, { id: 'b', text: '200-500 tokens' }, { id: 'c', text: '5000 tokens' }, { id: 'd', text: 'Split by sentence only' }], correctOption: 'b', explanation: '200-500 tokens per chunk is generally optimal for RAG — small enough to be specific, large enough to contain full context.' },
    { id: 'q6', text: 'What should you set to prevent an agent loop from running forever?', options: [{ id: 'a', text: 'Temperature to 0' }, { id: 'b', text: 'A maximum number of steps' }, { id: 'c', text: 'max_tokens to 100' }, { id: 'd', text: 'Streaming mode' }], correctOption: 'b', explanation: 'Always set a maximum step limit on agentic loops to prevent infinite execution in case of unexpected behavior or tool failures.' },
    { id: 'q7', text: 'When is the Human-in-the-Loop pattern most appropriate?', options: [{ id: 'a', text: 'For simple FAQ chatbots' }, { id: 'b', text: 'For high-stakes decisions in medical, legal, or financial contexts' }, { id: 'c', text: 'For generating marketing copy' }, { id: 'd', text: 'For code autocomplete' }], correctOption: 'b', explanation: 'Human-in-the-Loop is critical for high-stakes decisions where errors have serious consequences — medical, legal, financial, or safety-critical applications.' },
  ],
}
