import type { Quiz } from '@/types/content'
export const quiz: Quiz = {
  id: 'module-06-quiz', moduleSlug: 'module-06-advanced', title: 'Advanced Features — Quiz', passingScore: 70, xpReward: 50,
  questions: [
    { id: 'q1', text: 'What is the main benefit of streaming responses?', options: [{ id: 'a', text: 'Lower API cost' }, { id: 'b', text: 'Users see text appearing immediately instead of waiting for completion' }, { id: 'c', text: 'More accurate responses' }, { id: 'd', text: 'Longer context window' }], correctOption: 'b', explanation: 'Streaming delivers tokens as they\'re generated, so users see text appearing in real time rather than waiting for the full response.' },
    { id: 'q2', text: 'What parameter enables Extended Thinking in the API?', options: [{ id: 'a', text: 'chain_of_thought: true' }, { id: 'b', text: 'reasoning_mode: "extended"' }, { id: 'c', text: 'thinking: { type: "enabled", budget_tokens: N }' }, { id: 'd', text: 'think_deeply: true' }], correctOption: 'c', explanation: 'Extended Thinking is enabled with the thinking parameter: { type: "enabled", budget_tokens: N } where N is the token budget for reasoning.' },
    { id: 'q3', text: 'How long does prompt cache content remain valid?', options: [{ id: 'a', text: '24 hours' }, { id: 'b', text: '1 hour' }, { id: 'c', text: '5 minutes of inactivity' }, { id: 'd', text: 'Forever until deleted' }], correctOption: 'c', explanation: 'Prompt cached content expires after 5 minutes of inactivity. If requests come more frequently, the cache stays warm.' },
    { id: 'q4', text: 'What is the approximate cost saving for a prompt cache HIT?', options: [{ id: 'a', text: '10% cheaper' }, { id: 'b', text: '50% cheaper' }, { id: 'c', text: '90% cheaper' }, { id: 'd', text: 'Cache hits are free' }], correctOption: 'c', explanation: 'Prompt cache hits are approximately 90% cheaper than reprocessing the same tokens, making it highly valuable for apps with large, reused contexts.' },
    { id: 'q5', text: 'What is the main use case for the Files API?', options: [{ id: 'a', text: 'Generating image files' }, { id: 'b', text: 'Upload a file once and reference it by ID in multiple requests' }, { id: 'c', text: 'Storing conversation history' }, { id: 'd', text: 'Downloading Claude\'s outputs as files' }], correctOption: 'b', explanation: 'The Files API lets you upload a document once and reuse it across multiple API calls by referencing its file ID, avoiding repeated uploads.' },
    { id: 'q6', text: 'When is Extended Thinking most useful?', options: [{ id: 'a', text: 'For simple factual Q&A' }, { id: 'b', text: 'For very long text generation' }, { id: 'c', text: 'For complex reasoning, math, and multi-step analysis' }, { id: 'd', text: 'For image analysis tasks' }], correctOption: 'c', explanation: 'Extended Thinking shines on complex reasoning tasks — math problems, strategic analysis, multi-step logic — where careful deliberation significantly improves accuracy.' },
  ],
}
