import type { Quiz } from '@/types/content'
export const quiz: Quiz = {
  id: 'module-07-quiz', moduleSlug: 'module-07-production', title: 'Safety & Best Practices — Quiz', passingScore: 70, xpReward: 50,
  questions: [
    { id: 'q1', text: 'Which error type should NOT be retried?', options: [{ id: 'a', text: 'APIConnectionError' }, { id: 'b', text: 'RateLimitError' }, { id: 'c', text: 'AuthenticationError' }, { id: 'd', text: 'APIStatusError 500' }], correctOption: 'c', explanation: 'Authentication errors indicate an invalid API key — retrying won\'t help. Fix the key first. Network and rate limit errors can be retried.' },
    { id: 'q2', text: 'What retry strategy should you use for rate limit errors?', options: [{ id: 'a', text: 'Retry immediately and repeatedly' }, { id: 'b', text: 'Wait exactly 60 seconds then retry once' }, { id: 'c', text: 'Exponential backoff (2s, 4s, 8s...)' }, { id: 'd', text: 'Switch to a different model' }], correctOption: 'c', explanation: 'Exponential backoff — doubling the wait time with each retry — is the standard strategy for rate limit errors to avoid hammering the API.' },
    { id: 'q3', text: 'Where should Anthropic API calls be made in a web application?', options: [{ id: 'a', text: 'Directly in browser JavaScript' }, { id: 'b', text: 'In a server-side API route' }, { id: 'c', text: 'In a public CDN script' }, { id: 'd', text: 'In a browser Web Worker' }], correctOption: 'b', explanation: 'API calls must be made server-side to keep your API key secret. Never call Anthropic directly from browser JavaScript.' },
    { id: 'q4', text: 'What is the most cost-effective model for high-volume, simple classification tasks?', options: [{ id: 'a', text: 'Opus' }, { id: 'b', text: 'Sonnet' }, { id: 'c', text: 'Haiku' }, { id: 'd', text: 'All models cost the same' }], correctOption: 'c', explanation: 'Haiku is the most cost-efficient tier — roughly 20x cheaper than Opus — making it ideal for high-volume, simpler tasks.' },
    { id: 'q5', text: 'What is Anthropic\'s Constitutional AI?', options: [{ id: 'a', text: 'A set of legal agreements' }, { id: 'b', text: 'A training approach using principles to make Claude safe' }, { id: 'c', text: 'A government regulation compliance tool' }, { id: 'd', text: 'A content filtering API' }], correctOption: 'b', explanation: 'Constitutional AI is Anthropic\'s training method that teaches Claude to be helpful and harmless using a set of principles (a "constitution").' },
    { id: 'q6', text: 'What is the Batch API best suited for?', options: [{ id: 'a', text: 'Real-time chat applications' }, { id: 'b', text: 'Streaming responses' }, { id: 'c', text: 'Large offline workloads processed asynchronously' }, { id: 'd', text: 'Image generation' }], correctOption: 'c', explanation: 'The Batch API processes up to 100,000 requests asynchronously with results available within 24 hours — at 50% lower cost than real-time.' },
  ],
}
